### ISSUE TITLE
ideas for Group AI motion control

### ISSUE THREAD

**Issue by XMaster96** [XRobots/openDog#11]
He,
I love your Open Dog project.
I'm interested in developing a AI (Neural Network), based motion control for your robot and I would like do do it as a group project. 

The problem is, that it would make no sense, if you don't wont it and you don't integrated it in to your OpenDog. Also I need your help finding people how are interested in it to.

Please don't mistake me for some on how don't now the challenges, of such a project. My plan is to Model the robot in a 3D environment, to train a Neural Network with reinforcement learning. I used reinforcement learning in the past, and I now that it is clearly possible to train a AI that can work. I don't now how well the trained AI will translate to the real robot. I guess that it will go ok, based on some papers I have read on this subject.

so if you are interested in this, or you have some additional questions, please contact me.

**Comment by XRobots** [comment]
I'm interested in this, but it'll have to come later on in the project. I think I'd probably mentioned it in a video and set up some sort of collaboration tool like Slack/Discord for interested parties.
